### ISSUE TITLE
can not find "tensorflow/cc/ops/dataset_ops_internal.h"?

### ISSUE THREAD

**Issue by weizaixl** [rockzhuang/tensorflow#5]
In the dataset example tfrecord_test2.cc, there is included file 
#include "tensorflow/cc/ops/dataset_ops_internal.h"'
but I can not find it, how can I solve the problem, thanks

**Comment by rockzhuang** [comment]
Please check the corresponding commit  https://github.com/rockzhuang/tensorflow/commit/489e04e1deeeb0c187b06aa3749e9383d341a37b
Some modification in BUILD file are required.
